groups:
- name: {{ component }} - {{env}}
  rules:
  - alert: CPU Usage alert
    expr: avg by (instance) (100 - (rate(node_cpu_seconds_total{mode="idle"}[5m]) * 100)) > 70
    for: 1m
    keep_firing_for: 5m
    labels:
      severity: warning
      component: {{ component }}
      env: {{env}}
    annotations:
      summary: Warning | CPU usage alert
  - alert: CPU Usage alert
    expr: avg by (instance) (100 - (rate(node_cpu_seconds_total{mode="idle"}[5m]) * 100)) > 90
    for: 1m
    keep_firing_for: 5m
    labels:
      severity: critical
      component: {{ component }}
      env: {{env}}
    annotations:
      summary: Warning | CPU usage alert      
  - alert: CPU Usage alert
    expr: ((node_memory_MemFree_bytes + node_memory_Cached_byte + node_memory_Buffers_bytes) / node_memory_MemTotal_bytes) * 100 > 70
    for: 1m
    keep_firing_for: 5m
    labels:
      severity: critical
      component: {{ component }}
      env: {{env}}
    annotations:
      summary: Warning | CPU usage alert            
      
