- name: expense frontend
  hosts: all
  became: yes
  tasks:
     - name: install nginx service
       ansible.builtin.dnf:
         name: nginx
         state: present
     - name: copy the expense.conf file
       ansible.builtin.template:
         src: expense.conf
         dest: /etc/nginx/default.d/expense.conf
     - name: remove the content
       ansible.builtin.file:
         path: /usr/share/nginx/html/* 
         state: absent
     - name: download and extract the content
       ansible.builtin.unarchive:
         src: https://expense-artifacts.s3.amazonaws.com/frontend.zip
         dest: /tmp/frontend.zip
     - name: enable and restart the service
       ansible.builtin.systemd:
         name: nginx
         state: restarted
         enable: yes     
         

