     - name: install nginx service
       ansible.builtin.dnf:
         name: nginx
         state: present
     - name: copy the expense.conf file
       ansible.builtin.template:
         src: expense.conf
         dest: /etc/nginx/default.d/expense.conf

     - name: import role
       ansible.builtin.import_role:
        name: common
        task_from: app-prereq
       vars:
        app_dir: /usr/share/nginx/html/*
        component: frontend
     - name: enable and restart the service
       ansible.builtin.systemd:
         name: nginx
         state: restarted
         enabled: yes     
         

