    - name: disable mysql
      ansible.builtin.shell: dnf module disable mysql -y 
    - name: install mysql
      ansible.builtin.dnf:
       name: mysql-community-server 
       state: present
    - name: copy backend.service
      ansible.builtin.template:
        src: mysql.repo
        dest: /etc/yum.repos.d/mysql.repo
    - name: setting the password
      ansible.builtin.shell: mysql_secure_installation --set-root-pass "{{ lookup('amazon.aws.aws_ssm', 'mysql.{{env}}.DB_PASS', region='us-east-1' ) }}"

    - name: systemd services
      ansible.builtin.systemd:
       name: mysqld
       state: restarted
       enabled: yes  

       
         