- name: copy the service file
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml
- name: copy the alertrules
  ansible.builtin.template:
    src: alertrules.yml
    dest: /opt/prometheus/alertrules.yml
- name: restart the prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted
    enabled: yes
   