- name: copy the service file
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml
- name: copy the alertrules
  ansible.builtin.template:
    src: common.yml
    dest: /opt/prometheus/alert-rules/common.yml
- name: register the output
  amazon.aws.s3_object:
    bucket: prometheus-alert-rules.yml
    mode: list
  register: out

- name: Download all the objects from the s3 buckets related alert files
  amazon.aws.s3_object:
    bucket: prometheus-alert-rules.yml
    mode: get
    object: "{{item}}"
    dest: /opt/prometheus/alert-rules/{{item}}
  loop: "{{out.s3_keys}}"  

- name: Reload Prometheus
  ansible.builtin.shell: kill -1 $(ps -ef | grep /opt/prometheus/prometheus | grep -v grep  | awk '{print $2}')
- name: copy the alertmanager
  ansible.builtin.template:
    src: alertmanager.yml
    dest: /opt/alertmanager/alertmanager.yml

    
- name: reload the alert manager
  ansible.builtin.shell: kill -1 $(ps -ef | grep /opt/prometheus/prometheus | grep -v grep | awk '{print $2}')




