route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'SNS'
receivers:
  - name: SNS
    sns_configs:
      - sigv4:
          region: us-east-1            # AWS region for signing requests
        topic_arn: arn:aws:sns:us-east-1:831926604528:alertmanager
        subject: 'some_subject'
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
