groups:
- name: example
  rules:
  - alert: Instance down alert
    expr: up < 1
    for: 1m
    keep_firing_for: 5m
    labels:
      severity: critical
    annotations:
      summary: Instance down alert